name: Docker Image CI

on:
  push:
    branches: 
      - "main"
      - feature/*

  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - shell: bash
      run: |
        echo hello pipe

